#version 460
#extension GL_EXT_nonuniform_qualifier : enable
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set=0, binding = 1, r32f) uniform image3D tensors[];
layout(set=0, binding = 3) buffer SSBO {
    float data[];
} buffers[];

layout(push_constant) uniform PushConstants {
    uint prev_act;
    uint next_grad_act;
    uint grad_weights;
    uint in_dim;
    uint out_dim;
    uint sc_dim;
    uint input_is_texture;
} pc;

void main(){
    uint i = gl_GlobalInvocationID.x;
    uint j = gl_GlobalInvocationID.y;
    if(i >= pc.in_dim || j >= pc.out_dim) return;

    uint sq = pc.sc_dim * pc.sc_dim;
    uint idx = j * pc.in_dim + i;
    float m;
    if(pc.input_is_texture > 0){
        uint c = i / sq;
        uint y = (i / pc.sc_dim) % pc.sc_dim;
        uint x = i % pc.sc_dim;

        m = imageLoad(
            tensors[nonuniformEXT(pc.prev_act)],
            ivec3(x, y, c)
        ).r;

        //m = imageLoad(tensors[nonuniformEXT(pc.prev_act)],ivec3(0,0,i)).r;
    }else{
        m = buffers[nonuniformEXT(pc.prev_act)].data[i];
    }

    float val = buffers[nonuniformEXT(pc.next_grad_act)].data[j] * m;
    buffers[nonuniformEXT(pc.grad_weights)].data[idx] = val;
}