#version 460
#extension GL_EXT_nonuniform_qualifier : enable
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set=0, binding = 3) buffer SSBO {
    float data[];
} buffers[];

layout(push_constant) uniform PushConstants {
    uint next_grad_act;
    uint grad_bias;
    uint out_dim;
} pc;

void main(){
    uint i = gl_GlobalInvocationID.x;
    if(i >= pc.out_dim) return;

    buffers[nonuniformEXT(pc.grad_bias)].data[i] = buffers[nonuniformEXT(pc.next_grad_act)].data[i];
}