#version 460
#extension GL_EXT_nonuniform_qualifier : enable
layout(local_size_x = 8, local_size_y = 1, local_size_z = 1) in;

layout(set=0, binding = 3) buffer SSBO {
    float data[];
} buffers[];

layout(push_constant) uniform PushConstants {
    uint next_grad_act;
    uint grad_act;
    uint weights;
    uint in_dim;
    uint out_dim;
    uint relu;
    uint act;
} pc;

void main(){
    uint i = gl_GlobalInvocationID.x;
    if(i >= pc.in_dim) return;

    float sum = 0.;

    for(uint j = 0; j < pc.out_dim; j++){
        uint w_idx = j * pc.in_dim + i;
        sum += buffers[nonuniformEXT(pc.weights)].data[w_idx] * buffers[nonuniformEXT(pc.next_grad_act)].data[j];
    }

    if(pc.relu != 0){
        if(buffers[nonuniformEXT(pc.act)].data[i] <= 0.) sum = 0.;
    }

    buffers[nonuniformEXT(pc.grad_act)].data[i] = sum;
}