#version 460
#extension GL_EXT_nonuniform_qualifier : enable
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set=0, binding = 1, r32f) uniform image3D tensors[];
layout(set=0, binding = 3) buffer SSBO {
    float data[];
} buffers[];

layout(push_constant) uniform PushConstants {
    uint next_grad_act;
    uint grad_act;
    uint indices;
    uint out_w; // w//2
    uint out_h; // h//2
    uint ch;
    uint in_w; // w, for winner unpacking
} pc;

void main(){
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    uint c = gl_GlobalInvocationID.z;
    if(x >= pc.out_w || y >= pc.out_h || c >= pc.ch) return;

    uint out_idx = c * (pc.out_w * pc.out_h) + y * pc.out_w + x;
    uint winner = floatBitsToUint(buffers[nonuniformEXT(pc.indices)].data[out_idx]);

    float grad = imageLoad(tensors[nonuniformEXT(pc.next_grad_act)], ivec3(x, y, c)).r;

    ivec3 idx = ivec3(winner % pc.in_w, winner / pc.in_w, c);
    float val = imageLoad(tensors[nonuniformEXT(pc.grad_act)], idx).r + grad;
    imageStore(tensors[nonuniformEXT(pc.grad_act)], idx, vec4(val));
}