#version 460
#extension GL_EXT_nonuniform_qualifier : enable
layout(local_size_x = 8, local_size_y = 8, local_size_z = 3) in;

layout(set=0, binding = 1, r32f) uniform image3D images[];
layout(set=0, binding = 2) buffer SSBO {
    float data[];
} buffers[];

layout(push_constant) uniform PushConstants {
    uint buffer_input;
    uint image_output;

    uint image_width;
    uint image_height;
} pc;

void main() {
    ivec3 texel = ivec3(gl_GlobalInvocationID.xyz);
    ivec2 size = ivec2(pc.image_width,pc.image_height);
    if (texel.x >= size.x || texel.y >= size.y) return;

    uint sample_linear = (texel.x+texel.y*size.x)*3+texel.z;
    float col = buffers[nonuniformEXT(pc.buffer_input)].data[sample_linear];

    imageStore(images[nonuniformEXT(pc.image_output)],texel,vec4(col));
}